### PR TITLE
support attributes for restrictions of base complex types

### PR DESCRIPTION
**Pull request by Guite**

### CODE REVIEW

**Comment by goetas** [comment]
looks good, can you please add some tests for it?

**Comment by Guite** [comment]
added new tests to `RestrictionsTest` :-)

**Comment by goetas** [comment]
thanks for the test improvements

**Comment by EddyK77** [comment]
Hi guys. I'm a savvy in computer systems,  and I'm looking for a profi -
who knows where to look exactly to confront a cheating partner 🤔.  It's a
nightmare to know about it, but not being able to prove it! Everyone thinks
that I am a crazy 🤪 one and go on my partners side, and against me! I am
practically lost my three kids- they are trying to believe me, but my
partner erases all data right away, sometimes in front of me, but kids
don't see those moments. Guys, please help me someone 😢 🙏.  Maybe if you
can't, you can recommend someone? 😉  But please not very expensive one.
Thanks in advance ☺️.

**Pull request merged**
