### PR TITLE
Psalm

### PR DESCRIPTION
**Pull request by SignpostMarv**
re-enabled psalm, fixed some static analysis issues.

### CODE REVIEW

**Comment by SignpostMarv** [comment]
psalm is identifying an issue on 1110 of SchemaReader, not sure how to correct it there.

**Comment by goetas** [comment]
cant see the issue? what does it says?

**Comment by SignpostMarv** [comment]
```sh
 41/41 [============================] 100%> php ./vendor/vimeo/psalm/psalm
ERROR: InvalidArrayAccess - src\SchemaReader.php:1110:59 - Cannot access array value on non-array variable $this->globalSchema of type GoetasWebservices\XML\XSDReader\Schema\Schema
        } elseif ($namespace && !$schemaLocation && isset($this->globalSchema[$namespace])) {


ERROR: InvalidArrayAccess - src\SchemaReader.php:1111:32 - Cannot access array value on non-array variable $this->globalSchema of type GoetasWebservices\XML\XSDReader\Schema\Schema
            $schema->addSchema($this->globalSchema[$namespace]);


ERROR: MixedArgument - src\SchemaReader.php:1111:32 - Argument 1 of GoetasWebservices\XML\XSDReader\Schema\Schema::addSchema cannot be mixed, expecting GoetasWebservices\XML\XSDReader\Schema\Schema
            $schema->addSchema($this->globalSchema[$namespace]);


Checks took 0.39915704727173 and used 23.642MB
Script php ./vendor/vimeo/psalm/psalm handling the tests event returned with error code 1

```

**Comment by goetas** [comment]
my bad. should be `self::$globalSchemaInfo[$namespace]` instead of `$this->globalSchema[$namespace]`

**Comment by SignpostMarv** [comment]
https://github.com/goetas-webservices/xsd-reader/blob/c51bd4f9f3cb5e61c56a280c2e8945f7ad215c67/src/SchemaReader.php#L1081

self::$globalSchemaInfo[$namespace] is a string, wondering where the Schema should come from?

**Comment by goetas** [comment]
fixed in https://github.com/goetas-webservices/xsd-reader/pull/30

**Comment by SignpostMarv** [comment]
will get that merged in tonight.

**Comment by SignpostMarv** [comment]
following up with scrutinizer re: php-scrutinizer-run timeout

**Comment by goetas** [comment]
merged! thanks! :)

**Comment by SignpostMarv** [comment]
you're welcome :)

**Pull request merged**
