### PR TITLE
Restriction Validation for Simple Types

### PR DESCRIPTION
**Pull request by davidsonalencar**
It has been prepared for support on the creation of simple type class PHP and provide the necessary validations on the restrictions.

### CODE REVIEW

**Comment by goetas** [comment]
wow, this looks cool :tada: @davidsonalencar great job! will try to review it as soon as possible

**Comment by goetas** [comment]
What is your idea on how to use this classes? what about generating YAML metadata for https://symfony.com/doc/current/validation.html and make it a separate component?

**Comment by davidsonalencar** [comment]
I'm thinking of something but I'm still maturing the idea. However, I created a suggestion in the project [xsd2php](https://github.com/goetas-webservices/xsd2php) to automatically generate simple type class with these validators.

Do you have any suggestions or improvement above this idea or about YAML metadata validator?

Following my suggestion:
    https://github.com/goetas-webservices/xsd2php/compare/master...davidsonalencar:master

**Comment by goetas** [comment]
I have already followed that path years ago.. and it did not well... if you are interested (and you plan to work on this project) we can have a quick chat over skype and explain you a bit more.

This PR is well done, but I have been already on this path, and I'm worried is going to be wrong again.

**Comment by davidsonalencar** [comment]
No problem! I don't think it's cool... I have a big XSD to transform in many classes and this one have many validations... I would take a long time to write on hand... So, for a while I need to work in this project. Anything I'm on the skype davidson-alencar to talk.

**Pull request closed without merging**
