### PR TITLE
Php 7.0

### PR DESCRIPTION
**Pull request by SignpostMarv**
lock file was merged back in, only ever had problems with it when testing between 5 & 7

scrutinzer quality dropped a teensy bit due to the duplication introduced in favour of strict return types.

### CODE REVIEW

**Comment by goetas** [comment]
hi! thanks a lot! will review it soon! 

(one thing, committing `composer.lock` for libraries is not recommended)

**Comment by SignpostMarv** [comment]
re: composer.lock, not recommended by who ?
as mentioned briefly in the PR description, I've only ever had issues with composer.lock being committed when used across PHP versions that have inherent compatibility issues (i.e. supporting libs for php 5 & php 7).

the big thing that concerns me in this PR is I couldn't figure out how to get travis to configure HHVM to be PHP-7 friendly- see 8ec9e7b & 3f3d7fc

**Comment by DerMika** [comment]
The Composer docs say this: 

> Note: For libraries it is not necessary to commit the lock file, see also: Libraries - Lock file.

"Not necessary". However when clicking through, [this is what they point to](https://getcomposer.org/doc/02-libraries.md#lock-file): 

> For your library you may commit the composer.lock file if you want to. This can help your team to always test against the same dependency versions. However, this lock file will not have any effect on other projects that depend on it. It only has an effect on the main project.

> If you do not want to commit the lock file and you are using git, add it to the .gitignore.

The way I see it, composer.lock is only relevant when developing the library itself and is not used in any way by projects including your library. So I don't see any reason to not commit it. [I have committed it for my library](https://github.com/amabnl/amadeus-ws-client).

**Comment by goetas** [comment]
@DerMika this library is tested on multiple php versions, so needs different dependencies.
testing it only with one configuration makes the multi php version tests useless

**Comment by SignpostMarv** [comment]
@goetas 7b1c3bd dropped php 5.6, so the multiple php version tests on travis are now about forward-compatiblity

Previously I was using `phpstan/phpstan:dev-master`, so a `composer.lock` entry would've been useful for ensuring we were all testing with the same version of phpstan (there were breaking changes in dev-master as the 0.9 releases were approaching), but with the 0.9.1 release that's less of an issue.

I would be happy with dropping the composer.lock file, so long as there's a policy of allowing it when doing `composer require` with package branches ?

**Comment by DerMika** [comment]
@goetas I don't really understand what dependencies you are worried about. Your library seems to only require PHP 5.6+ and PHPUnit for dev. The only thing committing `composer.lock` would achieve is that all developers of your library would be using the same PHPUnit version.

**Comment by SignpostMarv** [comment]
@DerMika prior to 7b1c3bd, running `composer update` under php 7 would leave you with a lock file that could contain dev dependencies that wouldn't install/run under 5.6

**Comment by DerMika** [comment]
Ah I see. 

You could fix that by adding an extra config to your `composer.json`:

```json
    "config": {
        "platform": {
            "php": "5.6"
        }
    },
```

Which would tell composer to target PHP 5.6 compatible dependencies.

Although of course at that point it doesn't really matter if you do this or just remove your lock file...

**Comment by SignpostMarv** [comment]
@DerMika I suppose that might be an option if @goetas wants to actively support a branch that's just for `php < 7.0` ?

**Comment by SignpostMarv** [comment]
i.e. tag 1b0b242 as `v0.2.7`, branch it to 0.3 w/ `composer require php:^5.6` then tag as `v0.3.0`, then merge this PR & tag it as `v0.4.0` (adding in the 5.6 requirement being a non-majorish "breaking change" from 0.2)

p.s. with my inevitable php 7.1 pr coming in as 0.5

**Comment by SignpostMarv** [comment]
looks like test setup is failing, probably a timeout waiting for travis to send the tests over?

**Comment by goetas** [comment]
aha, will check that soon!

**Comment by goetas** [comment]
@SignpostMarv thanks for the efforts you put into this!

**Comment by SignpostMarv** [comment]
you're welcome :)

**Pull request merged**
