### PR TITLE
Add easy way to run PHPUnit

### PR DESCRIPTION
**Pull request by holtkamp**

### CODE REVIEW

**Comment by goetas** [comment]
where is the easy part between this two options?

```
php composer run test
```
and

```
php vendor/bin/phpunit
```

including that for the second option you have path shell suggestion, a full set of phpunit features (not filtered by composer), and the second des not require to have the composer binary...

**Comment by holtkamp** [comment]
Uhm... I run:

```composer test```

additionally: now the user does need to know / remember:

- that PHPUnit is the testing framework
- how that works
- where the command is located

**Comment by goetas** [comment]
hmm.. 

```php
composer test
``` 

looks too much a composer command... and users may feel justified to not know what is phpunit... and how it works.

really not sure about this syntactical sugar...

**Comment by holtkamp** [comment]
>looks too much a composer command...

well... it **is** a composer script 😄 . Consider it an alias that helps (beginning) users to see what is possible. 

Remember the 'old' XSD2PHP commands? Ough, they were hard, so I created two scripts:

- composer generatePhpClasses
- composer generateYamlMetadata

pronto!

Now with the new XSD2PHP approach, I got a project 'myProject-api-crazyXmlStandard' which sole responsibility is provided the PHP classes and YAML metadata for that particular standard:

```json
"scripts": {
    "generate": "vendor/bin/xsd2php convert config.yml ./xsd/someCrazyXmlStandard/*.xsd"
  }
```

Everything to *not* remember such commands, which after a few months are forgotten...

But maybe it is just personal. I do not use PHPUnit a lot and always have to figure out how it works, etc.

**Comment by goetas** [comment]
I see your point in `"generate": "vendor/bin/xsd2php convert config.yml ./xsd/someCrazyXmlStandard/*.xsd"`... i had a project with a relativity complex command line, and now if I have to take it again, will spend probably a day to remember the full command.

Probably should have used composer scripts... for that project.

Regarding this project... probably will have to sleep over the idea of composer scripts... and digest them a bit better.

Do not plan to merge this, but will keep it open, in case I wake up in the night and realize that was a great idea :)

**Comment by goetas** [comment]
:+1:  no big deals

**Pull request merged**
